### ISSUE TITLE
include spring-cloud-stream.2.0.0.RELEASE

### ISSUE THREAD

**Issue by komushi** [spring-cloud-stream-app-starters/http#17]
I assume it is because of app-starters-core-dependencies.
What should I do to align with the latest version?

```
      <dependency>
        <groupId>org.springframework.cloud.stream.app</groupId>
        <artifactId>app-starters-core-dependencies</artifactId>
        <version>2.0.0.BUILD-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Comment by sabbyanandan** [comment]
This is complete. Please try the Darwin.SR2 release coordinates. More details here: https://github.com/spring-cloud-stream-app-starters/app-starters-release/releases/tag/vDarwin.SR1
