### ISSUE TITLE
"Unauthorized: Full authentication is required to access this resource" 

### ISSUE THREAD

**Issue by kartiklunkad26** [spring-cloud-stream-app-starters/http#2]
Seeing this message with the recent upgrade of Spring Boot when trying to post content to the http app deployed as part of the stream. 

Steps to reproduce: 
1. stream create --name httplog --definition "http | log"
2. stream deploy httplog
3. http post --contentType 'application/json' --target http://dataflow-server-kl-RzTsaC7-httplog-http.cfapps.haas-89.pez.pivotal.io --data "{\"name\": \"Foo\"}"

Error message: 
> POST (application/json;charset=UTF-8) http://dataflow-server-kl-RzTsaC7-httplog-http.cfapps.haas-89.pez.pivotal.io {"name": "Foo"}
> 401 UNAUTHORIZED
{
  "path" : "/",
  "error" : "Unauthorized",
  "message" : "Full authentication is required to access this resource",
  "timestamp" : 1487449221621,
  "status" : 401
}
Error sending data '{"name": "Foo"}' to 'http://dataflow-server-kl-RzTsaC7-httplog-http.cfapps.haas-89.pez.pivotal.io'

**Comment by sabbyanandan** [comment]
This has been addressed in 1.1.2.RELEASE via: https://github.com/spring-cloud-stream-app-starters/http/compare/v1.1.2.RELEASE...master. You can download the 1.1.2.RELEASE from [here](http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/http-source-rabbit/).

**Comment by kartiklunkad26** [comment]
That's super fast response, Sabby! Thanks!
